pub mod agent;
pub mod ascii;
pub mod combat;
pub mod directive;
pub mod hex;
pub mod mapgen;
pub mod observation;
pub mod pathfinding;
pub mod replay;
pub mod runner;
pub mod sim;
pub mod state;
pub mod vision;

pub const FOOD_RATE: f32 = 0.1;
pub const MATERIAL_RATE: f32 = 0.05;
pub const UNIT_FOOD_COST: f32 = 8.0;
pub const UNIT_MATERIAL_COST: f32 = 5.0;
pub const UPKEEP_PER_UNIT: f32 = 0.02;
pub const STARVATION_DAMAGE: f32 = 0.5;
pub const INITIAL_STRENGTH: f32 = 100.0;
pub const DAMAGE_RATE: f32 = 0.05;
pub const DISENGAGE_PENALTY: f32 = 0.3;
pub const BASE_MOVE_COOLDOWN: u8 = 2;
pub const TERRAIN_MOVE_PENALTY: f32 = 0.5;
pub const VISION_RADIUS: i32 = 5;
pub const INITIAL_UNITS: usize = 5;
pub const TICKS_PER_SECOND: u32 = 10;
pub const AGENT_POLL_INTERVAL: u32 = 5;
